# https://mise.jdx.dev/getting-started.html for docs :) 
[env]
SOPS_AGE_KEY_FILE = "{{config_root}}/age.agekey"
TALOSCONFIG = "{{config_root}}/provision/talos/talosconfig"
KUBECONFIG = "{{config_root}}/provision/talos/kubeconfig"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"

[tools]
"aqua:casey/just" = "1.46.0"
"aqua:cilium/cilium-cli" = "0.19.2"
"aqua:cli/cli" = "2.87.3"
"aqua:cloudflare/cloudflared" = "2026.2.0"
"aqua:cue-lang/cue" = "0.15.4"
"aqua:evilmartians/lefthook" = "2.1.1"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.8.0"
"aqua:getsops/sops" = "3.12.1"
"aqua:helm/helm" = "4.1.1"
"aqua:helmfile/helmfile" = "1.3.2"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:kubernetes/kubernetes/kubectl" = "1.35.1"
"aqua:mikefarah/yq" = "4.52.4"
"aqua:siderolabs/talos" = "1.12.4"
"aqua:yannh/kubeconform" = "0.7.0"
"pipx:flux-local" = "latest"
"pipx:makejinja" = "2.8.2"
