---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-center
components:
  - ../../components/sops
resources:
  # TODO: maybe recyclarr and/or configarr?
  - bazarr/ks.yaml
  - jellyfin/ks.yaml
  - seer/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
  - sonarr/ks.yaml
  - qbit/ks.yaml
  - qui/ks.yaml
  - pvc.yaml
  - namespace.yaml
