---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Renovate'

on:
  workflow_dispatch:

  schedule:
    - cron: '*/30 * * * *' # Every half an hour
  push:
    branches: ['main']

permissions:
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: 'debug'
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: '${{ github.repository }}'
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_BOT_NAME: 'SirMergington'
  RENOVATE_HOST_RULES: | # private registries/repos
    [{"hostType": "docker", "matchHost": "ghcr.io", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]

jobs:
  renovate:
    name: Renovate
    runs-on: i7
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: '${{ secrets.BOT_APP_ID }}'
          private-key: '${{ secrets.BOT_APP_PRIVATE_KEY }}'

      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          token: '${{ steps.app-token.outputs.token }}'

      - name: Renovate
        uses: renovatebot/github-action@03026bd55840025343414baec5d9337c5f9c7ea7 # v44.0.4
        with:
          configurationFile: .renovate.json5
          token: '${{ steps.app-token.outputs.token }}'
