---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Renovate'

on:
  workflow_dispatch:

  schedule:
    - cron: '*/30 * * * *' # Every half an hour
  push:
    branches: ['main']

permissions:
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: 'debug'
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: '${{ github.repository }}'
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_BOT_NAME: 'SirMergington'
  RENOVATE_HOST_RULES: | # private registries/repos
    [{"hostType": "docker", "matchHost": "ghcr.io", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]

jobs:
  renovate:
    name: Renovate
    runs-on: i7
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: '${{ secrets.BOT_APP_ID }}'
          private-key: '${{ secrets.BOT_APP_PRIVATE_KEY }}'

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          token: '${{ steps.app-token.outputs.token }}'

      - name: Renovate
        uses: renovatebot/github-action@8b7941943a108b2cc2150730963164aa8baeab8c # v44.2.2
        with:
          configurationFile: .renovate.json5
          token: '${{ steps.app-token.outputs.token }}'
